name: econet
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.5.0+1
  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^6.0.2

  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  firebase_auth: ^0.18.1+2
  cloud_firestore: ^0.14.1+3
  firebase_messaging: ^8.0.0-dev.10
  firebase_database: ^4.3.0
  google_maps_flutter: ^0.5.33
  path_provider: ^1.6.24
  geolocator: ^6.1.7
  # Para buscar coordenadas de direcciones
  geocoder: ^0.2.1

  url_launcher: ^5.7.10

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_svg: ^0.19.0
  # For handling updates in widgets, added for the gmaps custom popups but will be used more
  provider: ^4.3.2+2
  auto_size_text: ^2.1.0
  tinycolor: ^1.0.3
  google_sign_in: "^4.5.1"

  #for linking scrollers in searchFilters
  linked_scroll_controller: ^0.1.2

  #font awesome icons, ejemplo icon: FaIcon(FontAwesomeIcons.recycle)
  font_awesome_flutter: 8.10.0

  sprintf: "^4.0.0"

  #For app icon
  flutter_launcher_icons: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/fonts/
    - assets/artwork/
    - assets/launcher/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SFCompactDisplay
      fonts:
        - asset: assets/fonts/SFCompact/TrueType/SFCompactDisplay-Regular.ttf
    - family: SFMono
      fonts:
        - asset: assets/fonts/SFMono/TrueType/SFMono-Regular.ttf
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFPro/TrueType/SFProDisplay-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SFPro/TrueType/SFProDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFPro/TrueType/SFProDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/SFPro/TrueType/SFProDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFPro/TrueType/SFProDisplay-Regular.ttf
          weight: 400
    - family: SFProText
      fonts:
        - asset: assets/fonts/SFPro/TrueType/SFProText-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SFPro/TrueType/SFProText-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFPro/TrueType/SFProText-Light.ttf
          weight: 300
        - asset: assets/fonts/SFPro/TrueType/SFProText-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFPro/TrueType/SFProText-Regular.ttf
          weight: 400
    - family: Gilroy-Bold
      fonts:
        - asset: assets/fonts/Gilroy/TrueType/Gilroy-Bold.ttf
          weight: 700
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons/CustomIcons.ttf
    #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
